### ISSUE TITLE
[bug] The received string length is longer than maximum allowed (17 > 16)

### ISSUE THREAD

**Issue by zhogoshi** [hakan-krgn/hCore#31]
![image](https://user-images.githubusercontent.com/85288982/178592750-b8c42909-e895-4c21-ab56-8f13b44446ed.png)
just making default npc (with 4.1.0 all seems good but npc lags)
![image](https://user-images.githubusercontent.com/85288982/178592824-17a91a2c-ad96-459d-ac62-aec3b0de9484.png)

**Comment by hakan-krgn** [comment]
Hello, the first error is probably related to the scoreboard, I'm already recoding the scoreboard system. And the second issue is related to skin, because hCore gets npc skin from mojang database and this causes lag. When the player joins the server, you can try to get the skin as async and keep it until the player leaves the game.

**Comment by zhogoshi** [comment]
prob skins yeah, coz im not using. scoreboards rn, tysm <3

**Comment by zhogoshi** [comment]
same problem
![image](https://user-images.githubusercontent.com/85288982/178904899-acf575e7-80f4-4990-adbc-c7934f13909b.png)

**Comment by zhogoshi** [comment]
when im calling create method it just kicks me with this reason

**Comment by zhogoshi** [comment]
oh now it works. again, tysm for answering <3
